# Generated by Django 4.2.3 on 2023-07-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=10)),
                ('content_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('decription', models.TextField()),
                ('category', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('create_data', models.DateField(auto_now_add=True)),
                ('read_time', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
                ('content', models.ManyToManyField(to='api.contentarticle')),
            ],
        ),
    ]
