# Generated by Django 4.2.3 on 2023-07-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_articles_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='content_title',
            field=models.CharField(max_length=100),
        ),
    ]
